# Homework 03 

## Katie Hutschenreuter
## Due Tuesday, February 16th

In [1]:
import numpy as np

### 1. Vector manipulation

Create a vector of zeros of size 10 but have the fifth value be 1.

In [14]:
a=np.zeros(10)
a[5]=1
a

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

### 2. Vector range

Create a vector with values ranging from 10 to 49, inclusive.

In [17]:
b=np.linspace(10,49)
b

array([ 10.        ,  10.79591837,  11.59183673,  12.3877551 ,
        13.18367347,  13.97959184,  14.7755102 ,  15.57142857,
        16.36734694,  17.16326531,  17.95918367,  18.75510204,
        19.55102041,  20.34693878,  21.14285714,  21.93877551,
        22.73469388,  23.53061224,  24.32653061,  25.12244898,
        25.91836735,  26.71428571,  27.51020408,  28.30612245,
        29.10204082,  29.89795918,  30.69387755,  31.48979592,
        32.28571429,  33.08163265,  33.87755102,  34.67346939,
        35.46938776,  36.26530612,  37.06122449,  37.85714286,
        38.65306122,  39.44897959,  40.24489796,  41.04081633,
        41.83673469,  42.63265306,  43.42857143,  44.2244898 ,
        45.02040816,  45.81632653,  46.6122449 ,  47.40816327,
        48.20408163,  49.        ])

### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element. The API should be

    return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed

Include this (or an equivalent description) in the function's docstring.

In [6]:
def reverse(x):
    '''return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed'''
    
    res=x[::-1]
    return res

x=np.random.rand(10)
print('x = ',x)
print('res = ',reverse(x))


x =  [ 0.98264566  0.47838511  0.21810108  0.19628157  0.92191223  0.08546716
  0.90060253  0.79432761  0.67315762  0.40398425]
res =  [ 0.40398425  0.67315762  0.79432761  0.90060253  0.08546716  0.92191223
  0.19628157  0.21810108  0.47838511  0.98264566]


### 4. Find indices of non-zero elements

Write a function `find_nonzero(x)` that finds the indices of non-zero elements, with an API like

    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices

Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

In [8]:
def find_nonzero(x):
    '''return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices'''
    ind = np.where(x!=0)
    return ind[0]

c=np.array([1,2,0,0,4,0])
ind = find_nonzero(c)
print('ind = ',ind)    
    

ind =  [0 1 4]


### 5. Array with random values

Create a 3x3x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.

In [16]:
d=np.random.normal(0.0,1.0,(3,3,3))
d

array([[[ -3.24882940e-01,  -9.35289292e-01,  -7.74547416e-01],
        [  5.05615221e-01,  -1.06392239e+00,   9.54122721e-01],
        [  1.32252572e+00,   3.26919086e+00,  -5.15210613e-01]],

       [[ -5.64248341e-01,  -4.46124725e-01,  -1.79853186e-01],
        [ -5.73053252e-01,   1.05903302e+00,   9.31550903e-01],
        [ -5.60446546e-01,  -2.71918877e-01,  -7.41880972e-02]],

       [[  3.99880540e-01,   9.16217052e-01,   4.24908217e-01],
        [ -3.18450774e-01,  -5.68698534e-01,   3.73093446e-01],
        [  1.20324647e+00,  -7.59244727e-01,  -1.29706119e-03]]])

### 6. Operations on an array with random values

Create a 10x10 array with random values. Find 
- the minimum value of the 2nd row
- the maximum value of the 4th column

In [4]:
e=np.random.rand(10,10)
min_2=np.amin(e,axis=1)[1]
max_4=np.amax(e,axis=0)[3]
print('The minimum value of row 2 = ',min_2)
print('The maximum value of row 4 = ',max_4)

The minimum value of row 2 =  0.052453680807
The maximum value of row 4 =  0.919089468584


### 7. Vector without end points

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [19]:
f=np.linspace(0,1,12,endpoint=True)[1:11]
f
#I know there has to be a better way to do this but I can only figure out
#how to not include 1 not 0.

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

### 8. Sorted random vector

Create a random vector of size 10, then sort it.

In [17]:
g=np.random.rand(10)
print('g = \n',g)
g.sort()
print('g sorted = \n',g)

g = 
 [ 0.06920415  0.46032954  0.60904596  0.70786765  0.78886588  0.03459583
  0.1650901   0.76924152  0.28425151  0.9456133 ]
g sorted = 
 [ 0.03459583  0.06920415  0.1650901   0.28425151  0.46032954  0.60904596
  0.70786765  0.76924152  0.78886588  0.9456133 ]


### 9. Test for array equality

Write a function `is_equal(A, B)` that compare two arrays `A` and `B` and checks to see if they are equal. 

    return True if two arrays are the same shape and all the elements are equal.
    
    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.

The arrays count as equal if they are the same shape and all elements in the array are equal.

In [58]:
def is_equal(A,B):

    h=A.shape!=B.shape              #Tests if A and B are the same shape
    if A.shape==B.shape:          
        i=np.where(A==B)            #Finds the indices where A and B are the same
        newA=A[i]                   #Creates newA with the indices that are the same
        h=newA.shape==B.shape       #Tests if shape of newA and B are the same
    return h

A=np.linspace(1,5,5)
B=np.linspace(1,5,5)
is_equal(A,B)

True

### 10. Subtract the row mean from rows of a matrix

Create a matrix. Then subtract the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [19]:
i=np.arange(15).reshape(3,5)
s=i.shape
m=np.mean(i,axis=1).reshape(s[0],1)
new_matrix = i-m
print('Origional matrix = \n',i)
print('New matrix = \n',new_matrix)

Origional matrix = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
New matrix = 
 [[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


### 11. Multiply arrays

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [93]:
j=np.random.rand(5,5,3)
k=np.random.rand(5,5)
l=np.random.rand(3,5,5)
#num1=j*k              #Operands could not be broadcast
num2=l*k               #Returns an array with shape (3,5,5)

(3, 5, 5)

### 12. Creating a new array

Starting with an array

    Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
    
Generate an array 

    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [20]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print('Z = \n',Z)
R=[Z[i:i+4] for i,num in enumerate(Z[0:11])]
print('R = \n',R)


Z = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
R = 
 [array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9]), array([ 7,  8,  9, 10]), array([ 8,  9, 10, 11]), array([ 9, 10, 11, 12]), array([10, 11, 12, 13]), array([11, 12, 13, 14])]


### 13. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is

    Return equivalent polar coordinates of specified cartesian points.
    
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively



In [101]:
def cart2polar(xy):
    '''Return equivalent polar coordinates of specified cartesian points.

    Inputs:
    xy: array
         Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
    rp: array
        Nx2 array of polar coordinates, with columns radius and angle respectively'''
    x=xy.T[0]
    y=xy.T[1]
    r=np.sqrt((x**2)+(y**2))
    theta=np.arctan(y/x)
    rp=np.array([r,theta]).T
    return rp

nums=np.random.rand(10,2)
cart2polar(nums)

array([[ 0.36427008,  1.47960262],
       [ 1.17752442,  0.97638685],
       [ 1.03498626,  0.47405164],
       [ 0.70116397,  1.03270574],
       [ 0.79636328,  0.29332645],
       [ 0.97429402,  1.52326294],
       [ 0.99174344,  1.07796572],
       [ 0.96867355,  0.2825646 ],
       [ 0.7766216 ,  1.3377241 ],
       [ 0.81452067,  0.99296515]])

### 14. Compute and time for loops and array operations.

Calculate the time it takes to do what we did in class

    a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
    b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
    sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

and the time required for doing the same operation with a series of 4 `for` loops, one for each dimension of the arrays. Compare the times by calculating a ratio.

In [17]:
#Done
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

import time
t_start=time.time()

sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

t_stop=time.time()
t_passed_1=t_stop-t_start
print('{:6.4f} seconds have passed.'.format(t_stop-t_start))

0.0002 seconds have passed.


In [18]:
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)  

import time
t_start=time.time()

solnew=np.ones(1024.0).reshape(4,8,16,2)
for i in list(range(4)):
    for j in list(range(8)):
        for k in list(range(16)):
            for l in list(range(2)):
                sol = a[i,j,k,l]*b[i,j,k,l]
                solnew[i,j,k,l]=sol

t_stop=time.time()
t_passed_2=t_stop-t_start
print('{:6.4f} seconds have passed.'.format(t_stop-t_start))
                

0.0025 seconds have passed.


In [19]:
print('{:6.4f}:1 is the ratio of for loop multiplication to element-by-element multiplication'.format(t_passed_2/t_passed_1))

10.9989:1 is the ratio of for loop multiplication to element-by-element multiplication


### 15. Fix the code

This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. Write out what you changed to make it work and why it needed to be changed.

In [ ]:
#Origional code
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [43]:
#Fixed code
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa = aa/ 4. 
    a[:2,:] = a[:2,:] - aa
    res=a.T*b
    
    return res.T
    

a = np.ones((3,2))
b = np.ones(3)*3

res=calculate(a,b)
print(res)
assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


I changed the syntax of the 2nd and 3rd lines of the function 

    aa /= 4 --> aa= aa/4 
    a[:2,:] -= aa --> a[:2,:]=a[:2,:]-aa
    
I changed what the function returned to make the matrix dimensions agree
I multiplied a.T*b instead of a*b so the inner dimensions matched (both=3)
I returned res.T to make the assertion statement true

### 16. Calculate components of a vector

Read in file `data/burl1h2010.txt`. This file gives a bunch of data from a wind station. In particular, read in the wind direction, `WDIR`, and wind speed, `WSPD`. Then, write a function that calculates and returns the `u` and `v` components of this wind vector, which point along the x- and y-axes.

The function should have the following basic functionality:

    Take in vector and return components.
    
    Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude
        
    Returns:
        u: x component of vector
        v: y component of vector



In [21]:
data = np.loadtxt('/Users/KatieHutschenreuter/Desktop/python4geosciences/data/burl1h2010.txt')
WDIR=data[:,5]
WSPD=data[:,6]

def polar2cart(vdir,vspd):
    '''Take in vector and return components.

    Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

    Returns:
    u: x component of vector
    v: y component of vector'''
    
    u=vspd*np.cos(vdir)
    v=vspd*np.sin(vdir)
    return [u,v]

[u,v]=polar2cart(WDIR,WSPD)
print('u = \n',u, '\nv = \n',v)

u = 
 [-1.39148661 -3.19668806 -1.21206139 ..., -9.04175518  4.27262701
  7.13235823] 
v = 
 [  2.65777445  -1.65565257  -3.06934964 ...,   6.94310185  11.10651423
  -7.29173958]


### 17. (Grad) Write and use a class

Consider one of the data files located in `python4geosciences/data/MCH/`. Write a class, `dataclass`, to store some of the information in the file. The class should:

* be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values found in the file;
* contain a method, `salt_mean`, which returns the mean of the salinity;
* contain a method, `temp_max`, which returns the maximum value of the temperature values.

Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. Instead, write a loop which loops through the file names, reads in the necessary data, calls `dataclass` to store the data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should have a list of all of the class instances, one for each data file.

Hint: Check out the package `glob` for reading in file names with a wild card. 

In [2]:
import glob
dirsearch='/Users/KatieHutschenreuter/Desktop/python4geosciences/data/MCH/*'
#np.('/Users/KatieHutschenreuter/Desktop/python4geosciences/data/MCH/m1001a.cnv2')

#temerature is column 3 of files or index 2
#salinity is column 6 of files or index 5
names=[]
for i,name in enumerate(glob.glob(dirsearch)):
    ind1 = name.find('m')
    ind2 = name.find('.')
    names.append(name[ind1:ind2])

In [15]:
#initializes a class to save temp and salinity
class dataclass(object):
    
    def __init__(self, obj):
        self.obj=obj
        self.temp = obj[:,2]
        self.salt = obj[:,5]
        
    def salt_mean(self):
        'Returns the mean of the salinity'
        return np.mean(self.salt)
    
    def temp_max(self):
        'Returns the maximum temperature value'
        return np.amax(self.temp)

#loops through each file and performs salt_mean and temp_max and saves them
#to var1 and var2
#Do I also need to save the salinity and temperature variables?
#Is there a way to convert the string name into a variable name so each 
#class is defined differently and is not overwritten?
var1 = []
var2 = []
temperature = []
salinity = []
for i,name in enumerate(names):
    ob = np.loadtxt('/Users/KatieHutschenreuter/Desktop/python4geosciences/data/MCH/'+name+'.cnv2',skiprows=57)
    values = dataclass(ob)
    temperature.append(values.temp)
    salinity.append(values.salt)
    var1.append(values.salt_mean())
    var2.append(values.temp_max())

print('Average salinity = \n',var1,'\n')
print('Maximum temperatures = \n',var2,'\n')
print('Temperature values = \n',temperature,'\n')
print('Salinity values = \n',salinity)

Average salinity = 
 [24.658829411764707, 24.567600000000002, 30.681368571428571, 32.676372499999999, 32.488624999999999, 35.606388461538458, 26.5899, 26.652857894736844, 33.478300000000004, 27.187711111111113, 31.675515624999999, 34.35348611111111, 34.624456097560973, 34.905857446808511, 30.201615000000004, 31.693000000000001, 28.031300000000002, 31.934872727272733, 34.256788235294117, 33.032632432432436, 34.76672095238095, 35.203648148148147, 34.918039583333332, 34.997901754385964, 35.779000000000011, 35.641005263157901, 30.763772222222219, 31.139225, 35.943934666666664, 34.160930188679245, 35.176372222222227, 28.43919285714286, 34.821384745762707, 33.401621621621615, 34.759034751773051, 35.406458536585369, 35.176737500000002, 22.222399999999997, 36.294326760563386, 28.41893125, 34.919819298245613, 31.088217391304347, 33.790099999999995, 35.366065116279067, 35.561194285714286, 35.207217999999997, 35.828874999999996] 

Maximum temperatures = 
 [22.120100000000001, 22.1937, 21.6295, 21

### 18. (Grad) Running mean

Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.

Do not use the `pandas` package or the function `convolve`; instead, use a loop. Use the following API for your function:

    Return the running average of a vector, with averaging window of size N.
    
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
    Outputs:
        out: Vector of running-averaged values; same size as vec



In [24]:
def runningavg(vec,N):
    '''Return the running average of a vector, with averaging window of size N.

    Inputs:
    vec: Input vector
    N (int): Averaging window size, or number of elements to include in mean on either side of each element.

    Outputs:
    out: Vector of running-averaged values; same size as vec'''
    
    out=np.ones(len(vec))
    if N==0:
        out=vec
        return out
    else:
        if type(N)!=int:
            return 'N must be an integer value.'
        else:
            for i in list(range(len(vec))):
                if i-N<0:
                    out[i]=np.mean(vec[0:i+(N+1)])
                    continue
                elif i+N>len(vec):
                    out[i]=np.mean(vec[i-N:len(vec)])
                    continue
                elif i-N<0 and i+N>len(vec):
                    out[i]=np.mean(vec)
                    continue
                else:
                    out[i]=np.mean(vec[i-N:i+(N+1)])
                    continue
            return out

vec=np.array([1,2,3,6,53,6,120])
N=1
out=runningavg(vec,N)
print('The origional vector =\n',vec)
print('The running average of the vector =\n',out)

The origional vector =
 [  1   2   3   6  53   6 120]
The running average of the vector =
 [  1.5          2.           3.66666667  20.66666667  21.66666667
  59.66666667  63.        ]
